import daisyui from "daisyui"

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,vue,scss}", "./demo/src/**/*.{html,js,vue,scss}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  safelist: [
    'bg-primary',
    'bg-primary-content',
    'bg-secondary',
    'bg-secondary-content',
    'bg-accent',
    'bg-accent-content',
    'bg-neutral',
    'bg-neutral-content',
    'bg-base-100',
    'bg-base-200',
    'bg-base-300',
    'bg-base-content',
    'bg-info',
    'bg-info-content',
    'bg-success',
    'bg-success-content',
    'bg-warning',
    'bg-warning-content',
    'bg-error',
    'bg-error-content',
    'btn-primary',
    'btn-primary-content',
    'btn-secondary',
    'btn-secondary-content',
    'btn-accent',
    'btn-accent-content',
    'btn-neutral',
    'btn-neutral-content',
    'btn-base-100',
    'btn-base-200',
    'btn-base-300',
    'btn-base-content',
    'btn-info',
    'btn-info-content',
    'btn-success',
    'btn-success-content',
    'btn-warning',
    'btn-warning-content',
    'btn-error',
    'btn-error-content',
    'text-primary',
    'text-primary-content',
    'text-secondary',
    'text-secondary-content',
    'text-accent',
    'text-accent-content',
    'text-neutral',
    'text-neutral-content',
    'text-base-100',
    'text-base-200',
    'text-base-300',
    'text-base-content',
    'text-info',
    'text-info-content',
    'text-success',
    'text-success-content',
    'text-warning',
    'text-warning-content',
    'text-error',
    'text-error-content',
    'text-transparent',
    'step',
    'steps',
    'modal',
    'modal-box',
    'btn',
    'btn-sm',
    'btn-circle',
    'btn-ghost',
    'absolute',
    'right-2',
    'top-2',
    'shadow-lg',
    'w-full',
    'rounded-xs',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'hidden',
    'block',
  ],
}

